//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Kayıt_Sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDER
    {
        public short OGRID { get; set; }
        public string OGRNUMARA { get; set; }
        public string OGRAD { get; set; }
        public string OGRSOYAD { get; set; }
        public Nullable<byte> OGRS1 { get; set; }
        public Nullable<byte> OGRS2 { get; set; }
        public Nullable<byte> OGRS3 { get; set; }
        public Nullable<decimal> ORTALAMA { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
